name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Fetch ASAR
      run: 
        wget https://github.com/RPGHacker/asar/archive/refs/tags/v1.91.zip
        unzip v1.91.zip
        cmake src
        make
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
